Repository DemoyDW/energy-monitor, pull requests merged in 2025-10, with the labels that each got.

#83 Extract complete with tests
  etl_pipeline/outages/extract_outages_csv.py
  etl_pipeline/outages/requirements.txt
  etl_pipeline/outages/test_extract_outages_csv.py
  etl_pipeline/outages/transform_outages.py
Labels: documentation, enhancement

#88 Test transform carbon intensity
  etl_pipeline/power_readings/extract_carbon.py
  etl_pipeline/power_readings/test_transform_carbon.py
  etl_pipeline/power_readings/transform_carbon.py
Labels: testing

#98 added a parent .gitignore file to the repo
  .gitignore
Labels: security

#100 Making the rds publicly accessible
  terraform/main.tf
Labels: bug, database

#101 Fixed datetime reading to be on the hour and half/hour and removed unnecessary imports
  etl_pipeline/power_readings/transform_carbon.py
Labels: bug

#103 completed architecture diagram
  diagrams/architecture_diagram.png
Labels: documentation

#104 Setting up the ECRs through terraform
  terraform/README.md
  terraform/main.tf
Labels: infrastructure

#106 Power readings
  .gitignore
  etl_pipeline/power_readings/extract.py
  etl_pipeline/power_readings/requirements.txt
  etl_pipeline/power_readings/test_extract.py
Labels: testing

#114 Removed constant global variables
  etl_pipeline/power_readings/transform.py
Labels: enhancement

#112 Load script to upload to power_reading table
  etl_pipeline/power_readings/load_power.py
  etl_pipeline/power_readings/requirements.txt
Labels: enhancement, database

#117 Fix ERD on architecture diagram
  diagrams/architecture_diagram.png
  etl_pipeline/power_readings/extract_carbon.py
Labels: documentation, infrastructure

#128 Docker for the outages
  etl_pipeline/outages/Dockerfile
  etl_pipeline/outages/requirements.txt
Labels: enhancement, infrastructure

#119 Changes to schema
  etl_pipeline/database/schema.sql
  etl_pipeline/database/seed.sql
Labels: enhancement, database

#127 Feature load power carbon main load
  etl_pipeline/carbon_readings/README.md
  etl_pipeline/carbon_readings/requirements.txt
  etl_pipeline/power_readings/extract_carbon.py
  etl_pipeline/power_readings/extract_power.py
  etl_pipeline/power_readings/load_carbon.py
  etl_pipeline/power_readings/load_main.py
  etl_pipeline/power_readings/load_power.py
  etl_pipeline/power_readings/requirements.txt
  etl_pipeline/power_readings/test_extract.py
  etl_pipeline/power_readings/test_transform_power.py
  etl_pipeline/power_readings/transform.py
  etl_pipeline/power_readings/transform_carbon.py
  etl_pipeline/power_readings/transform_power.py
Labels: enhancement, database

#132 Setting up initial dockerfile for dashboard
  dashboard/dockerfile
Labels: dashboard

#134 Schema change
  etl_pipeline/database/schema.sql
Labels: bug, database

#156 Fix carbon power date_time issue
  dashboard/carbon_insights.py
  dashboard/carbon_insights_charts.py
  dashboard/data.py
  etl_pipeline/power_readings/test_transform_carbon.py
  etl_pipeline/power_readings/transform_carbon.py
  etl_pipeline/power_readings/transform_power.py
Labels: bug, database

#161 Queries needed for weekly summary report
  newsletter/newsletter_queries.py
  newsletter/requirements.txt
Labels: enhancement

#159 Dashboard sign up
  dashboard/requirements.txt
  dashboard/sign_up.py
Labels: enhancement, dashboard

#169 Email report - Subscribers emails - docker file
  newsletter/dockerfile
  newsletter/newsletter_queries.py
  newsletter/requirements.txt
  newsletter/summary_report_html.py
Labels: enhancement, database, dashboard

#176 Fixed indentation problem
  etl_pipeline/outages/power_outages_emails.py
Labels: bug
